apiVersion: apps/v1
kind: Deployment
uses: matootie/dokube@v1.3.4
with:
  clusterName: k8s-bergen
  personalAccessToken: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
